### ISSUE TITLE
Calendar - Upcoming Celestial events

### ISSUE THREAD

**Issue by omgthegreenranger** [omgthegreenranger/Astrono-MyDashboard#1]
Calendar will display major events in astronomy/space:
- Rocket/satellite launches/changes
- meteor showers
- eclipses
- etc.

Might be able to be local to coordinates if possible.

Will be done when:
- [x] A list of events that will scroll down the right side of the page
- [x] Will indicate month, date, time of event (where applicable)
- [x] Will include a link to more information if available (from the NASA or other reputable source)

Nice-to-have
- [x] full sized calendar on click
- [x] centred on user's chosen location.

**Comment by YaroslavVolvach** [comment]
Added "Events"
